// LogiLED – Script 3
var SCRIPT_1=1,SCRIPT_2=2,SCRIPT_3=3;
function configureStartup(){Shelly.call("Script.Stop",{id:SCRIPT_1});Shelly.call("Script.SetConfig",{id:SCRIPT_1,config:{enable:false,auto_start:false}});Shelly.call("Script.Stop",{id:SCRIPT_2});Shelly.call("Script.SetConfig",{id:SCRIPT_2,config:{enable:false,auto_start:false}});Shelly.call("Script.SetConfig",{id:SCRIPT_3,config:{auto_start:true}})}
configureStartup();
function page(){return "<!doctype html><html lang=de data-theme=dark><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>LogiLED</title><style>"+
":root{--background-color:#11191f;--color:hsl(205,16%,77%);--h1-color:hsl(205,20%,94%);--h2-color:#e1e6eb;--muted-color:hsl(205,10%,50%);--muted-border-color:#1f2d38;--primary:hsl(195,85%,41%);--primary-hover:hsl(195,80%,50%);--card-background-color:#141e26;--card-border-color:#141e26;--spacing:1rem;--block-spacing-vertical:calc(var(--spacing)*2);--typography-spacing-vertical:1rem;--border-radius:.25rem;--transition:200ms ease}*{box-sizing:border-box}body{width:100%;margin:0;background:var(--background-color);color:var(--color);font:16px system-ui,-apple-system,'Segoe UI',sans-serif;line-height:1.5}body>footer,body>header,body>main{width:100%;margin:auto;padding:var(--block-spacing-vertical) 0}.container{width:100%;margin:auto;padding:0 var(--spacing)}@media(min-width:576px){.container{max-width:510px;padding:0}}@media(min-width:768px){.container{max-width:700px}}@media(min-width:992px){.container{max-width:920px}}@media(min-width:1200px){.container{max-width:1130px}}nav{display:flex;align-items:center;justify-content:space-between}nav ul{display:flex;align-items:center;gap:1rem;margin:0;padding:0;list-style:none}nav li{list-style:none;margin:0}nav a{color:var(--primary);text-decoration:none}nav strong{color:var(--h1-color)}main{min-height:calc(100vh - 150px)}.grid{display:grid;gap:var(--spacing);grid-template-columns:1fr}@media(min-width:992px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}article{margin:0;padding:var(--spacing);border:1px solid var(--card-border-color);border-radius:var(--border-radius);background:var(--card-background-color);box-shadow:0 .03rem .2rem #0004}article h2{margin:0 0 var(--spacing);color:var(--h2-color);font-size:1rem}article.output{grid-row:span 2}.output-body{min-height:250px;display:flex;align-items:center;justify-content:center;gap:2rem}.ring{width:160px;height:160px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(var(--primary) 0 70%,#33434e 70%)}.ring:after{content:'';grid-area:1/1;width:134px;height:134px;border-radius:50%;background:var(--card-background-color)}.power{grid-area:1/1;z-index:1;color:var(--muted-color);font-size:3rem}.output-buttons{display:flex;flex-direction:column;gap:.5rem}.output-buttons button{width:145px;margin:0;padding:.55rem .75rem;background:#24333e;color:var(--color);border:1px solid #374956;border-radius:var(--border-radius);font:inherit;text-align:left}.row{display:flex;justify-content:space-between;padding:.55rem 0;border-bottom:1px solid var(--muted-border-color)}.row:last-child{border-bottom:0}.muted{color:var(--muted-color)}footer{border-top:1px solid var(--muted-border-color);color:var(--muted-color);font-size:.875rem}.foot{display:flex;justify-content:space-between}@media(max-width:650px){.output{grid-row:auto}.output-body{flex-direction:column}.foot{gap:.5rem;flex-direction:column}}</style></head><body>"+
"<header><nav class=container><ul><li><strong>Shelly</strong></li><li><a href='#' aria-current=true>LogiLED</a></li></ul><ul aria-hidden=true><li>◌</li><li>⚙</li><li>⋮</li></ul></nav></header>"+
"<main class=container><div class=grid><article class=output><h2>OUTPUT()</h2><div class=output-body><div class=ring><div class=power>⏻</div></div><div class=output-buttons><button>Power</button><button>Animation</button><button>Einstellungen</button></div></div></article>"+
"<article><h2>Leistung</h2><div class=row><span class=muted>Aktuell</span><strong id=p>—</strong></div><div class=row><span class=muted>Spannung</span><strong id=v>—</strong></div><div class=row><span class=muted>Strom</span><strong id=i>—</strong></div></article>"+
"<article><h2>Status</h2><div class=row><span class=muted>Ausgang</span><strong id=o>—</strong></div><div class=row><span class=muted>Temperatur</span><strong id=t>—</strong></div></article></div></main>"+
"<footer><div class='container foot'><span id=d>LogiLED</span><span id=f>—</span></div></footer><script>function x(i,v){document.getElementById(i).textContent=v==null?'—':v}function j(u){return fetch(u).then(function(r){return r.json()})}Promise.all([j('/rpc/Switch.GetStatus?id=0'),j('/rpc/Shelly.GetDeviceInfo')]).then(function(a){var s=a[0],d=a[1];x('p',s.apower+' W');x('v',s.voltage+' V');x('i',s.current+' A');x('o',s.output?'Ein':'Aus');x('t',s.temperature&&s.temperature.tC+' °C');x('d',d.name||d.id);x('f',d.ver?'Shelly '+d.ver:'—')}).catch(function(){x('f','Daten nicht verfügbar')});</script></body></html>"}
HTTPServer.registerEndpoint("site",function(req,res){res.code=200;res.headers=[["Content-Type","text/html; charset=utf-8"]];res.body=page();res.send()});
